name: mysisterfred
favicon: null
layout_spectrum: 0.7041594332549721
typography_spectrum: 0.921318699605763
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4206792959012091
  lightness: 0.9255669587291777
  saturation: 0.8249265570193529
  rhythmicContrast: 0.5740304212085903
purpose: []
